import { BaseEntity } from './../../shared';

export class Organizacio implements BaseEntity {
    constructor(
        public id?: number,
        public vNumexpedi?: string,
        public vDesorgani?: string,
        public tFecregist?: any,
        public vDessiglas?: string,
        public vNumresolu?: string,
        public cDesdocruc?: number,
        public tFecpresen?: any,
        public tFecconsta?: any,
        public vCorreo?: string,
        public cTelefono?: string,
        public vEstado?: string,
        public vDirecreal?: string,
        public vDirelegal?: string,
        public vTafiliaci?: string,
        public vDescalifi?: string,
        public nUbigeo?: number,
        public nNumdnisin?: string,
        public vObservaci?: string,
        public nNumciiu?: number,
        public nUsuareg?: number,
        public tFecreg?: any,
        public nFlgactivo?: boolean,
        public nSedereg?: number,
        public nUsuaupd?: number,
        public tFecupd?: any,
        public nSedeupd?: number,
        public srubro?: BaseEntity,
        public tipoorganiz?: BaseEntity,
        public nivelorgani?: BaseEntity,
        public ambitoorgan?: BaseEntity,
        public categoria?: BaseEntity,
        public categoriaor?: BaseEntity,
        public region?: BaseEntity,
        public szonal?: BaseEntity,
        public librosindics?: BaseEntity[],
        public recursos?: BaseEntity[],
        public empresas?: BaseEntity[],
        public estatutos?: BaseEntity[],
        public palabraclavs?: BaseEntity[],
        public documents?: BaseEntity[],
        public federacions?: BaseEntity[],
        public sindicatoes?: BaseEntity[],
        public delegados?: BaseEntity[],
        public juntadirects?: BaseEntity[],
        public afiliados?: BaseEntity[],
        public calificacio?: BaseEntity,
    ) {
        this.nFlgactivo = false;
    }
}
