
package pe.gob.trabajo.service.wsstd;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "serviciosstd", targetNamespace = "http://ws.web.bs.std.mef.gob.pe/", wsdlLocation = "http://192.168.140.137:8080/tramite/webservice/serviciosstd?wsdl")
public class Serviciosstd_Service
    extends Service
{

    private final static URL SERVICIOSSTD_WSDL_LOCATION;
    private final static WebServiceException SERVICIOSSTD_EXCEPTION;
    private final static QName SERVICIOSSTD_QNAME = new QName("http://ws.web.bs.std.mef.gob.pe/", "serviciosstd");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.140.137:8080/tramite/webservice/serviciosstd?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOSSTD_WSDL_LOCATION = url;
        SERVICIOSSTD_EXCEPTION = e;
    }

    public Serviciosstd_Service() {
        super(__getWsdlLocation(), SERVICIOSSTD_QNAME);
    }

    public Serviciosstd_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOSSTD_QNAME, features);
    }

    public Serviciosstd_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOSSTD_QNAME);
    }

    public Serviciosstd_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOSSTD_QNAME, features);
    }

    public Serviciosstd_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Serviciosstd_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Serviciosstd
     */
    @WebEndpoint(name = "ServiciosSTDPort")
    public Serviciosstd getServiciosSTDPort() {
        return super.getPort(new QName("http://ws.web.bs.std.mef.gob.pe/", "ServiciosSTDPort"), Serviciosstd.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Serviciosstd
     */
    @WebEndpoint(name = "ServiciosSTDPort")
    public Serviciosstd getServiciosSTDPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.web.bs.std.mef.gob.pe/", "ServiciosSTDPort"), Serviciosstd.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOSSTD_EXCEPTION!= null) {
            throw SERVICIOSSTD_EXCEPTION;
        }
        return SERVICIOSSTD_WSDL_LOCATION;
    }

}
