import { BaseEntity } from './../../shared';

export class Legajo implements BaseEntity {
    constructor(
        public id?: number,
        public vCodreg?: string,
        public vCodzon?: string,
        public vCodpas?: string,
        public vCodmat?: string,
        public vNumexp?: string,
        public vNomjuzg?: string,
        public vNomjuez?: string,
        public vEstleg?: string,
        public dFecconc?: any,
        public vCodusureg?: string,
        public vHostreg?: string,
        public vCodusumod?: string,
        public dFecmod?: any,
        public vHostmod?: string,
        public dFecexp?: any,
        public vNumleg?: string,
        public vCodemp?: string,
        public nCodsuc?: number,
        public vFlginst?: string,
        public vNumexpda?: string,
        public dFecexpda?: any,
        public vNomjuzda?: string,
        public vNomjuezda?: string,
        public vCodlegrig?: string,
        public vTiporig?: string,
        public vFlgarch?: string,
        public vFlgcaut?: string,
        public vFlganul?: string,
        public vCodloc?: string,
        public nUsuareg?: number,
        public tFecreg?: any,
        public nFlgactivo?: boolean,
        public nSedereg?: number,
        public nUsuaupd?: number,
        public tFecupd?: any,
        public nSedeupd?: number,
        public empleador?: BaseEntity,
        public pasegl?: BaseEntity,
        public trabajador?: BaseEntity,
        public abogado?: BaseEntity,
        public legtipdocs?: BaseEntity[],
        public atencionpjs?: BaseEntity[],
        public legajoasigs?: BaseEntity[],
        public materia?: BaseEntity,
    ) {
        this.nFlgactivo = false;
    }
}
