
package pe.gob.trabajo.service.wstramite;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "situacionmitramite", targetNamespace = "http://ws.web.bs.std.mef.gob.pe/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Situacionmitramite {


    /**
     * 
     * @param numero
     * @param anio
     * @return
     *     returns pe.gob.trabajo.service.wstramite.ExpedienteWSDto
     * @throws ErrorDeServicio
     */
    @WebMethod
    @WebResult(name = "expediente", partName = "expediente")
    public ExpedienteWSDto consultaExpediente(
        @WebParam(name = "anio", partName = "anio")
        int anio,
        @WebParam(name = "numero", partName = "numero")
        String numero)
        throws ErrorDeServicio
    ;

}
