export * from '../models/trabajador.model';
export * from '../models/pernatural.model';
export * from '../models/tipdocident.model';
export * from '../models/cartrab.model';
export * from '../models/motatenofic.model';
export * from '../models/perjuridica.model';
export * from '../models/docpresate.model';
// export * from './motate.service';
export * from '../models/motate.model';
export * from '../models/accionadop.model';
export * from './atencion-trabajador.service';
export * from './atencion-trabajador.component';
export * from './atencion-trabajador-wizard.component';
export * from './atencion-trabajador.route';
export * from './atencion-trabajador-wizard/datos-trabajador.component';
export * from './atencion-trabajador-wizard/motivos-consulta.component';
